name: Manual Trigger Test

on:
  workflow_dispatch:
    inputs:
      message: 
        description: 'The message to print'
        required: true
        default: 'Hello, GitHub Actions!' 
jobs:
  test-job:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
    
    - name: Print the message
      run: |
        echo "The message is: ${{ github.event.inputs.message }}"
        ls -l
        uname -a
