name: Manual Trigger Test

on:
  workflow_dispatch:
    inputs:
      message: 
        description: 'The message to print'
        required: true
        default: 'Hello, GitHub Actions!' 
jobs:
  test-job:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
      
    - name: make
      run: make pkg
      working-directory: main
    
    - name: Print the message
      run: |
        echo "The message is: ${{ github.event.inputs.message }}"
        ls -l main
        mkdir -p zipfiles
        mv main/*.zip zipfiles
        ls -l zipfiles
    - name: Upload build files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact   
        path: ./zipfiles/         
